export const environment = {
  production: true,
  useMockServices: true,
  trilha:false,
  idCurso: 0,
  curso:'Plataforma Mock',
  nome: 'Usuário Mock',
  turma:'Turma A',
  profile: 'ROLE_ADMIN',
  idUsuario: 1,
  idTurma: 1,
  hasCurriculo:false,
  token: 'mock-token',
  valorBarometroDia: '',
  valorBarometroVideo: '',
  temaModulo: '',
  corModulo: '',
  idModulo: 0,
  idEventoCronograma: 0,
  idVideoUpload: 0,
  titulo: '',
  icon: '',
  enviosBarometroDia: 0,
  respQuestVideo: false,
  idAula: 0,
  entregaPendente: 0,
  entregaPendenteOb: 0,
  color: '',
  server:'http://31.220.57.121',
  port: ':8060'
};
